# Generated by Django 6.0.2 on 2026-03-17 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logbook', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('revision_requested', 'Revision Requested'), ('rejected', 'Rejected')], max_length=30)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('Logbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='logbook.logbook')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
